# Generated by Django 4.0.6 on 2022-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='vive',
            field=models.BooleanField(default=True),
        ),
    ]
